### ISSUE TITLE
MRL Incidencia - Arreglar permisos votación por preferencia

### ISSUE THREAD

**Issue by Jeszamgue** [fernando-hidalgo/decide-part-murillo#100]
# 🚨 Problema detectado
Al hacer una votación por preferencia sin añadir a nadie en el censo por preferencia, deja votar a cualquiera.

# 🕵🏻 Replicación
Creación de una votación por preferencia, iniciarla y no añadir a nadie en el census, ir a la url booth/preference/id_votacion_preferencia, logearse con un usuario cualquiera y hacer la votación.

# ✅ Solución Propuesta
Cambiar el get usuario de census por preferencia por la url correcta en store.

**Comment by fravilpae** [comment]
Yo me encargo
