### ISSUE TITLE
MRL Incidencia - Arreglar permisos votación yes no

### ISSUE THREAD

**Issue by Jeszamgue** [fernando-hidalgo/decide-part-murillo#117]
# 🚨 Problema detectado
Al hacer una votación yesno sin añadir a nadie en el censo yesno, da un error 500, en vez de 401.

# 🕵🏻 Replicación
Creación de una votación por yesno, iniciarla y no añadir a nadie en el census, ir a la url booth/yesno/id_votacion_preferencia, logearse con un usuario cualquiera y hacer la votación.

# ✅ Solución Propuesta
Comprobar que los codigos de error esten bien puestos en store.

**Comment by Ramguerom** [comment]
Yo la hago
