### ISSUE TITLE
MRL48 - Mostrar votaciones normales disponibles en pág base

### ISSUE THREAD

**Issue by fravilpae** [fernando-hidalgo/decide-part-murillo#132]
# 🎯 Alcance:
- Voting

## 🧑 Descripción
En la pág. base, añadir un apartado donde una vez logueado se muestren las votaciones normales disponibles (*en las que el usuario logueado pueda votar*) y que te lleve a su respectiva cabina de votación

 ## 🔨 Criterios de Aceptación
- Se muestra la pág correctamente y se han realizado los tests necesarios

**Comment by fernando-hidalgo** [comment]
Concluido el tiempo del desarrollo ofrecido por la asignatura, se desestima esta tarea
