### ISSUE TITLE
MRL51 - Correo cada vez que se añade usuario a census

### ISSUE THREAD

**Issue by diegarlin** [fernando-hidalgo/decide-part-murillo#137]
# 🎯 Alcance:
- Census

## 🧑 Descripción
Mandar un correo electrónico a un usuario cada vez que se le añada a una votación

 ## 🔨 Criterios de Aceptación
- Que el correo llegue correctamente.

(funcionalidad exclusiva en local)

**Comment by diegarlin** [comment]
@Ramguerom @Jeszamgue Necesito que me aviséis cuando arregléis el mixnet para vuestras 2 votaciones

**Comment by agudevbon** [comment]
@diegarlin ya están corregidos todos los errores correspondientes con las mixnets de los distintos tipos de votaciones.

**Comment by AitorRD** [comment]
Tras el analisis de coverage realizado, se ha detectado que no existen tests para el envio de correo de confirmación @diegarlin

**Comment by AitorRD** [comment]
Tests realizados en #171
