### ISSUE TITLE
MRL52 - Creación interfaz para votaciones de múltiples opciones

### ISSUE THREAD

**Issue by iniruimar** [fernando-hidalgo/decide-part-murillo#141]
# 🎯 Alcance:
- Voting

## 🧑 Descripción
Crear la interfaz de booth para la votación de múltiples opciones.

 ## 🔨 Criterios de Aceptación
- Crear las interfaces correctamente con sus test correspondientes.

**Comment by paupenfer1** [comment]
Ya está implementado las votaciones con posibilidad multiple de choices, así que ya se puede crear las interfaces
