### ISSUE TITLE
MRL Config 2 - Linter CC

### ISSUE THREAD

**Issue by fernando-hidalgo** [fernando-hidalgo/decide-part-murillo#24]
Instalación de un linter de  Conventional Commits, pues si bién se ha acordado el uso del sistema, el linter protege el proyecto

**Comment by fernando-hidalgo** [comment]
[Gitlint](https://jorisroovers.com/gitlint/latest/installation/) instalado y añadido al requirements.txt, el modo pre-commit

**Comment by AitorRD** [comment]
El error que daba en el Build sucedió con el test que hice de selenium para testear la traducción, ya que no podía abrir ninguna interfaz grafica de chrome y me saltaba el error.

**Comment by AitorRD** [comment]
El error que me sucede al subir los commits es que cuando gitlint hacia el checkeo, tras corregir la sintaxis, la cual estaba correcta, me saltaba un error que decia que no encontraba la version gitlint-core necesaria para ejecutar el commit. Reinstale varias veces los requirements.txt e incluso cambie versiones de gitlint.
![IMG-20231113-WA0001](https://github.com/fernando-hidalgo/decide-part-murillo/assets/72505728/8b2dbeb8-0ebb-4135-b988-346452111635)

**Comment by fernando-hidalgo** [comment]
# ✅ Solución
El error parece estar fuera de nuestro control, por venir de una descarga fallida de ciertas librerías por parte del servidor que aloja Gitlint

Por tanto, una solución temporal a la espera de reintentarlo de nuevo más tarde es desinstalar por completo en linter, teniendo siempre en cuenta que el desarrollador debe respetar Conventional Commits, esta vez de forma manual

Para desinstalar el hook:
1. Activar la vista de archivos ocultos en el explorador del Sistema Operativo
2. Navegar a la carpeta oculta **.git/hooks** del repositorio
3. Eliminar los archivos **commit-msg**, **commit-msg.legacy** y **commit-msg.sample**

Hecho esto, ya se podrán realizar commits con normalidad
