### ISSUE TITLE
MRL06 - Interfaz propia para crear una votación completa

### ISSUE THREAD

**Issue by fernando-hidalgo** [fernando-hidalgo/decide-part-murillo#5]

**Comment by AitorRD** [comment]
Me encargaré de hacer traducible esta interfaz

**Comment by fernando-hidalgo** [comment]
Se descarta esta issue a petición del desarrollador, participará en otras incidencias con la compañera @paupenfer1

Por tanto, no será necesaria la traducción por parte de @AitorRD
