### ISSUE TITLE
MRL Incidencia - Local Settings no ingnorado

### ISSUE THREAD

**Issue by fernando-hidalgo** [fernando-hidalgo/decide-part-murillo#54]
# 🚨 Problema detectado
El archivo _local_settings.py_ no está siendo correctamente ignorado, aunque se muestra en el _.gitignore_, los desarrolladores pueden subir el archivo o cambios de este a su rama

# 🕵🏻 Replicación
Aplicar cambios a _local_settings.py_ y subirlos en el commit

# ✅ Solución Propuesta
Revisar _.gitignore_ para constatar si verdaderamente mal configurado, y cambiarlo para que ignore como debe

**Comment by ursgarsan** [comment]
El error fue que la ruta del archivo local_settings.py estaba mal puesta ya que dicho archivo de encontraba dentro de la carpeta decide por lo que en el .gitignore se cambió _local_settings.py_ por _decide/local_settings.py_ solucionando así el problema.
