### ISSUE TITLE
MRL Incidencia - Arreglo nombrado de commits

### ISSUE THREAD

**Issue by Jeszamgue** [fernando-hidalgo/decide-part-murillo#64]
🚨 Problema detectado

Algunos commits no siguen los conventional commits en algunas ramas y no pasan los conventionals commits en la pull request 
🕵🏻 Replicación

Subir commits que no cumplan los conventionals commits 
✅ Solución Propuesta

Crear una nueva rama mismo nombre terminada en -bis y replicar los commits en esa rama con el nombramiento correcto

**Comment by Ramguerom** [comment]
Yo también he tenido este problema.
Voy a realizar el mismo procedimiento en mi rama.
