### ISSUE TITLE
MRL07 - Frontend de administración de censo

### ISSUE THREAD

**Issue by fernando-hidalgo** [fernando-hidalgo/decide-part-murillo#7]

**Comment by davra02** [comment]
Terminado el frontend básico para la administración de censo, a la espera de cambios por diegarlin.

**Comment by diegarlin** [comment]
He terminado mi parte @davra02 haz pull de #13  .
Muchas Gracias

**Comment by AitorRD** [comment]
Me encargaré de hacer traducible esta interfaz @davra02

**Comment by AitorRD** [comment]
Integración finalizada en #162
