### ISSUE TITLE
MRL29 - Creacion censo votacion si no

### ISSUE THREAD

**Issue by Ramguerom** [fernando-hidalgo/decide-part-murillo#70]
🎯 Alcance:
Censo

🧑 Descripción
Creacion de un censo para la votación por preferencia para que se pueda realizar la votación

🔨 Criterios de Aceptación
Correcto funcionamiento del censo votación por preferencia

**Comment by fravilpae** [comment]
Yo te ayudo. Para hacerlo voy a necesitar lo que llevas hecho. Cuando puedas lo subes a develop

**Comment by Ramguerom** [comment]
Perfecto. En breve estará subido. Muchas gracias.
