### ISSUE TITLE
MRL Incidencia - Cambios perdidos en la edición de votos

### ISSUE THREAD

**Issue by paupenfer1** [fernando-hidalgo/decide-part-murillo#72]
# 🚨 Problema detectado
La tarea MRL-16 que estábamos realizando conjuntamente yo y iniruimar de Murillo-2 yo subí primero el commit de mi parte del cógido y después Iñigo hizo pull y realizó su parte del código y la subió. Yo al volver a hacer pull para tener la parte de Iñigo y tener la funcionalidad completa no me funcionaba y a Iñigo sí porque durante ese periodo de tiempo otro compañero hizo commit de una funcionalidad que tocaba el mismo fichero que nosotros.

# ✅ Solución Propuesta
Mayor comunicación con el equipo entero para saber que ficheros estamos modificando antes de subir cualquier commit para que no haya conflictos.

**Comment by iniruimar** [comment]
Si se necesitan realizar cambios en un mismo fichero para dos funcionalidades distintas, es necesario realizar una prueba de compatibilidad entre esas dos nuevas funcionalidades creadas. Si se encuentra un conflicto entre estas dos funcionalidades, realizar los cambios oportunos para que funcionen correctamente.

**Comment by fernando-hidalgo** [comment]
Queda resuelto este caso concreto mediante el uso del hotfix #46
