### ISSUE TITLE
MRL30 - Interfaz de votación si no

### ISSUE THREAD

**Issue by Ramguerom** [fernando-hidalgo/decide-part-murillo#73]
¿Alguien está interesado en hacer la interfaz de la votación si no?

**Comment by paupenfer1** [comment]
Me encargo de realizar la interfaz de votación si/no

**Comment by Ramguerom** [comment]
Perfecto. Muchas gracias.

**Comment by AitorRD** [comment]
Me encargo de hacer la interfaz traducible @Ramguerom @paupenfer1

**Comment by paupenfer1** [comment]
He creado la interfaz para las votaciones con preguntas de si o no, pero al comprobar el voto con tally, da error el tally.

**Comment by AitorRD** [comment]
Integración finalizada en #162
