### ISSUE TITLE
MRL25 - Problema con el coverage y los conventional commits

### ISSUE THREAD

**Issue by Domi-ATLAS** [fernando-hidalgo/decide-part-murillo#95]
La rama con la funcionalidad 25 ya esta lista para mergearse a develop, pero un mal commit me impide meterlo junto a una covertura menor a develop, todos estos errores son externos a mi persona, ya que son tests que han dejado de funcionar y que han tenido que ser rehechos para que funcionasen, a su vez que es imposible crear una rama igual a la mergear que no contenga ese mal commit, por errores en las migraciones, lo que me obliga hacer un merge obligatorio a pesar de que no se cumplan estas dos circustancias ajenas a mi persona.

**Comment by fernando-hidalgo** [comment]
Remitirse a la PR #91 para mas información sobre por qué esta issue está descartada
