### ISSUE TITLE
MRL34 - Creacion de interfaz de loginuser

### ISSUE THREAD

**Issue by iniruimar** [fernando-hidalgo/decide-part-murillo#96]
🎯 Alcance:
Almacenamiento

🧑 Descripción
Implementar el inicio de sesión con el nombre de usuario y la contraseña correspondiente para cuando esté finalizada la paǵina base

🔨 Criterios de Aceptación
Correcto funcionamiento del inicio de sesión de usuario.

**Comment by paupenfer1** [comment]
Si inicias sesión con un usuario que no está registrado salta un framework de Django.
Te parece bien hacer que salte un mensaje avisando de que ese usuario no existe y devuelva al inicio de sesión para volverlo a intentar?
